### ISSUE TITLE
uSync Complete v8.7.x - Release testing. 

### ISSUE THREAD

**Issue by KevinJump** [Jumoo/uSync.Complete.Issues#55]
Feature checklists for the release testing of uSync.Complete for _v8.7.

This issue is tracking the status of our shakedown testing for the Umbraco 8.7 release of uSync. [whats in that](https://github.com/KevinJump/uSync8/issues/119)

## Publisher
- [x] Scheduled publishing #53 
- [x] Track Culture & Hostnames with content public #43 
- [x] Track Public Access settings with content publish #41 
- [x] Publish on selected languages #39 
- [x] Deploy system files #40 
- [x] Hide Advanced options in publish dialog #38  
- [x] Make the progress bar 'bounce around' less during a publish #44 
- [x] Check new wider system syncing dialog #36 
- [x] Check new default configurations for servers #37

## Exporter
- [x] Exporter publisher override #48

**Comment by KevinJump** [comment]
feature locking this release - (pre Umbraco 8.7) - so we have less moving parts when the block editor release of Umbraco comes out. 

there are some breaking changes in the uSync version for this release so both will have to be released together.

**Comment by KevinJump** [comment]
Exporter publisher override, fixed in Exporter 8.7.0.4
